SELECT DISTINCT 
a.MANDANTE, a.EMPRESA,
de.UF,
a.INSTALACAO, a.CONTRATO,TO_NUMBER(a.CONTA_CONTRATO) AS CONTA_CONTRATO, a.PARCEIRO_NEGOCIO,
a.STATUS_INSTALACAO, a.STATUS_COMERCIAL, a.DATA_DE, a.DATA_ATE,
a.GRUPO_TENSAO, a.UNIDADE_LEITURA, a.ETAPA_LEITURA, a.SEQUENCIA_LEITURA, a.CLASSE_CALCULO, a.TIPO_TARIFA,
a.CLIENTE_LIVRE, a.SETOR_INDUSTRIAL, a.TIPO_INSTALACAO, a.SISTEMA, a.CLASSE_PRINCIPAL, a.CODIGO_SUBCLASSE,
a.SUBCLASSE, a.DETERMINACAO_CONTAS, a.NIVEL_TENSAO, a.SETOR_ATIVIDADE, a.BLOQUEIO_LEITURA, a.TIPO_VIP,
a.TIPO_SERVICO, a.LOCAL_CONSUMO, a.TIPO_LOCAL_CONSUMO, a.PERIMETRO, a.FASE, a.CONJUNTO_ANEEL, a.MICRO_GERADOR,
a.INST_MED_FISCAL, a.FLAG_LD, a.IRRIGANTE, a.MOTIVO_BLOQUEIO_CONTRATO,a.MOVE_IN,a.MOVE_OUT,
a.CONTRATO_ATIVO, a.RESPONSAVEL, a.MOTIVO_BLOQ_CC, a.MEIO_PAGAMENTO, a.CONTA_CONTRATO_COLETIVA, a.CATEGORIA_PARCEIRO_NEGOCIO, a.NOME,
a.ESTADO_CIVIL, a.GENERO, a.DATA_NASCIMENTO DATA_NASCIMENTO, a.NOME_MAE,TO_NUMBER(a.CPF) CPF, a.CNPJ, a.EMAIL, FORMATA_TELEFONE(a.TEL_FIXO) TEL_FIXO,
FORMATA_TELEFONE(a.TEL_MOVEL) TEL_MOVEL , a.ORGAO_EXP, a.OBJETO_LIGACAO, a.PONTO_REFERENCIA, a.POSTE, a.TRANSFORMADOR,
a.CHAVE, a.ALIMENTADOR, a.TRAFO, a.RAMAL, a.DISJUNTOR, a.MEDICAO_FISCAL, a.POTENCIA, a.ESTRUTURA_REGIONAL_POLITICA, a.REGIONAL, a.DISTRITAL,
a.COD_SECCIONAL, a.SECCIONAL, a.MUNICIPIO, a.COD_LOCALIDADE, a.LOCALIDADE, a.ENDERECO, a.NUMERO, a.COMPLEMENTO, a.COMPLEMENTO2, a.CEP, a.CODIGO_BAIRRO, a.BAIRRO,
a.CODIGO_IBGE, a.AGRUP_ESTRUTURA_REGIONAL, a.LOCAL_INSTALACAO as LOCAL_INSTALACAO, a.ID_LOCAL_INSTALACAO, a.LOCAL_INSTALACAO_MEDIDOR, a.MEDIDOR,
a.MEDIDOR_ANTERIOR, a.MEDIDOR_POSTERIOR, a.CALENDARIO_FABRICA, a.CONTROLE_EXPEDICAO, a.TIPO_CLIENTE, a.CONTRATO_CONCESSAO, a.DATA_DADOS,
a.COD_LOGRADOURO, a.SAZONALIDADE, a.TIPO_SMC,  a.GRP_CFIL, a.COD_REGIONAL, a.COD_DISTRITAL, a.COD_MUNICIPIO, a.BI, a.RG, a.RANI, a.CTPS, a.CNH, a.PASSAPORTE,
a.DOC, a.FORMULARIO, a.TC_MEDICAO, a.TP_MEDICAO, CORRIGIR_COORDENADAS(a.LATITUDE) LATITUDE, CORRIGIR_COORDENADAS(a.LONGITUDE) LONGITUDE, a.DATA_INSTALACAO_MEDIDOR,
a.INICIO_REL_CC INICIO_REL_CC, COUNT(CF.CONTA) AS FATURAS_ABERTO
FROM CEMAR.TAB_CADASTRO a
INNER JOIN OWEQTSRV.DP_ESTADO de ON a.EMPRESA = de.EMPRESA 
LEFT JOIN CEMAR.CARTEIRA CF ON LPAD(CF.CONTA, 12, 0) = A.CONTA_CONTRATO AND CF.DTA_LANCAMENTO >= SYSDATE - 180
WHERE a.CONTA_CONTRATO IS NOT NULL
AND a.NOME IS NOT NULL
AND (a.CPF IS NOT NULL OR a.CNPJ IS NOT NULL )
AND OWEQTSRV.VALIDA_CPF(a.CPF) = 1
GROUP BY a.MANDANTE, a.EMPRESA, de.UF, a.INSTALACAO, a.CONTRATO, a.CONTA_CONTRATO, a.PARCEIRO_NEGOCIO,
a.STATUS_INSTALACAO, a.STATUS_COMERCIAL, a.DATA_DE, a.DATA_ATE,
a.GRUPO_TENSAO, a.UNIDADE_LEITURA, a.ETAPA_LEITURA, a.SEQUENCIA_LEITURA, a.CLASSE_CALCULO, a.TIPO_TARIFA,
a.CLIENTE_LIVRE, a.SETOR_INDUSTRIAL, a.TIPO_INSTALACAO, a.SISTEMA, a.CLASSE_PRINCIPAL, a.CODIGO_SUBCLASSE,
a.SUBCLASSE, a.DETERMINACAO_CONTAS, a.NIVEL_TENSAO, a.SETOR_ATIVIDADE, a.BLOQUEIO_LEITURA, a.TIPO_VIP,
a.TIPO_SERVICO, a.LOCAL_CONSUMO, a.TIPO_LOCAL_CONSUMO, a.PERIMETRO, a.FASE, a.CONJUNTO_ANEEL, a.MICRO_GERADOR,
a.INST_MED_FISCAL, a.FLAG_LD, a.IRRIGANTE, a.MOTIVO_BLOQUEIO_CONTRATO,a.MOVE_IN,a.MOVE_OUT,
a.CONTRATO_ATIVO, a.RESPONSAVEL, a.MOTIVO_BLOQ_CC, a.MEIO_PAGAMENTO, a.CONTA_CONTRATO_COLETIVA, a.CATEGORIA_PARCEIRO_NEGOCIO, a.NOME,
a.ESTADO_CIVIL, a.GENERO, a.DATA_NASCIMENTO, a.NOME_MAE,a.CPF, a.CNPJ, a.EMAIL, a.TEL_FIXO,
a.TEL_MOVEL , a.ORGAO_EXP, a.OBJETO_LIGACAO, a.PONTO_REFERENCIA, a.POSTE, a.TRANSFORMADOR,
a.CHAVE, a.ALIMENTADOR, a.TRAFO, a.RAMAL, a.DISJUNTOR, a.MEDICAO_FISCAL, a.POTENCIA, a.ESTRUTURA_REGIONAL_POLITICA, a.REGIONAL, a.DISTRITAL,
a.COD_SECCIONAL, a.SECCIONAL, a.MUNICIPIO, a.COD_LOCALIDADE, a.LOCALIDADE, a.ENDERECO, a.NUMERO, a.COMPLEMENTO, a.COMPLEMENTO2, a.CEP, a.CODIGO_BAIRRO, a.BAIRRO,
a.CODIGO_IBGE, a.AGRUP_ESTRUTURA_REGIONAL, a.LOCAL_INSTALACAO, a.ID_LOCAL_INSTALACAO, a.LOCAL_INSTALACAO_MEDIDOR, a.MEDIDOR,
a.MEDIDOR_ANTERIOR, a.MEDIDOR_POSTERIOR, a.CALENDARIO_FABRICA, a.CONTROLE_EXPEDICAO, a.TIPO_CLIENTE, a.CONTRATO_CONCESSAO, a.DATA_DADOS,
a.COD_LOGRADOURO, a.SAZONALIDADE, a.TIPO_SMC,  a.GRP_CFIL, a.COD_REGIONAL, a.COD_DISTRITAL, a.COD_MUNICIPIO, a.BI, a.RG, a.RANI, a.CTPS, a.CNH, a.PASSAPORTE,
a.DOC, a.FORMULARIO, a.TC_MEDICAO, a.TP_MEDICAO, a.LATITUDE, a.LONGITUDE, a.DATA_INSTALACAO_MEDIDOR,
a.INICIO_REL_CC